### ISSUE TITLE
is:issue is:open when I run cd external/YOLOX/ pip install -r requirements.txt && python setup.py develop，ImportError: cannot import name '_C' from 'yolox' (/TOPICTrack-main/external/YOLOX/yolox/__init__.py)

### ISSUE THREAD

**Issue by wangtuo111** [holmescao/TOPICTrack#2]
@-V2:~/TOPICTrack-main/external/YOLOX$ python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    ext_modules=get_ext_modules(),
  File "setup.py", line 52, in get_ext_modules
    from yolox.layers import FastCOCOEvalOp
  File "/TOPICTrack-main/external/YOLOX/yolox/layers/__init__.py", line 5, in <module>
    from .fast_coco_eval_api import COCOeval_opt
  File "/TOPICTrack-main/external/YOLOX/yolox/layers/fast_coco_eval_api.py", line 13, in <module>
    from yolox import _C
ImportError: cannot import name '_C' from 'yolox' (/TOPICTrack-main/external/YOLOX/yolox/__init__.py)

**Comment by holmescao** [comment]
We have fixed the YOLOX installation problem, and please try again. Please do not hesitate to ask again if you have any problems.
