### ISSUE TITLE
I'm sorry for borthing you, but I encountered an issue while trying to reproduce the experiment in training the Re-ID model. I found that in fast-reid, it seems that nothing can be located.

### ISSUE THREAD

**Issue by howardpai1021** [holmescao/TOPICTrack#3]
I encountered an issue while trying to reproduce the experiment in training the Re-ID model. I found that in fast-reid, it seems that nothing inside .

**Comment by howardpai1021** [comment]
Eval Config:
USE_PARALLEL         : False                         
NUM_PARALLEL_CORES   : 8                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : /home/howardpai/TOPICTrack/external/TrackEval/error_log.txt
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : False                         
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : True                          

MotChallenge2DBox Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : results/gt/                   
TRACKERS_FOLDER      : results/trackers/             
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : ['gmot_test']                 
CLASSES_TO_EVAL      : ['pedestrian']                
BENCHMARK            : MOT17                         
SPLIT_TO_EVAL        : val                           
INPUT_AS_ZIP         : False                         
DO_PREPROC           : True                          
TRACKER_SUB_FOLDER   : data                          
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FOLDER        : None                          
SEQMAP_FILE          : None                          
SEQ_INFO             : None                          
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt   
SKIP_SPLIT_FOL       : False                         
Tracker file not found: results/trackers/MOT17-val/gmot_test/data/MOT17-02-FRCNN.txt
Traceback (most recent call last):
  File "external/TrackEval/scripts/run_mot_challenge.py", line 64, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "/home/howardpai/TOPICTrack/external/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 161, in __init__
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: gmot_test/data/MOT17-02-FRCNN.txt

Eval Config:
USE_PARALLEL         : False                         
NUM_PARALLEL_CORES   : 8                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : /home/howardpai/TOPICTrack/external/TrackEval/error_log.txt
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : False                         
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : True                          

MotChallenge2DBox Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : results/gt/                   
TRACKERS_FOLDER      : results/trackers/             
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : ['gmot_test_post']            
CLASSES_TO_EVAL      : ['pedestrian']                
BENCHMARK            : MOT17                         
SPLIT_TO_EVAL        : val                           
INPUT_AS_ZIP         : False                         
DO_PREPROC           : True                          
TRACKER_SUB_FOLDER   : data                          
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FOLDER        : None                          
SEQMAP_FILE          : None                          
SEQ_INFO             : None                          
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt   
SKIP_SPLIT_FOL       : False                         
Tracker file not found: results/trackers/MOT17-val/gmot_test_post/data/MOT17-02-FRCNN.txt
Traceback (most recent call last):
  File "external/TrackEval/scripts/run_mot_challenge.py", line 64, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "/home/howardpai/TOPICTrack/external/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 161, in __init__
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: gmot_test_post/data/MOT17-02-F



I try Evaluation part when I use exp=mot17_val dataset=MOT17 sh eval_metrics.sh it give me this feedback.
